version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: petzone_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: petzone_db
      POSTGRES_USER: vonhatphuongahihi
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petzone_network

volumes:
  postgres_data:

networks:
  petzone_network:
    driver: bridge
